[project]
name = "mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "joblib>=1.5.3",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
]
